title: serendipitjx's Homepage
page-top-title: serendipitjx
top-section-bg-text: Be what you wanna be
home-subtitle: Jingxuan Tang&ensp;|&ensp;唐靖轩
copyright-text: '&copy; serendipitjx 2025-2027. All Rights Reserved.'
